//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ShareManV3.databaseSelfMade
{

    public partial class Div_Intervall : PersistentBase
    {
        int fDID;
        [Key(true)]
        public int DID
        {
            get { return fDID; }
            set { SetPropertyValue<int>(nameof(DID), ref fDID, value); }
        }
        string fIntervall;
        [Indexed(Name = @"UniqueIntervall", Unique = true)]
        public string Intervall
        {
            get { return fIntervall; }
            set { SetPropertyValue<string>(nameof(Intervall), ref fIntervall, value); }
        }
        [Association(@"ShareReferencesDiv_Intervall")]
        public IList<Share> Shares { get { return GetList<Share>(nameof(Shares)); } }
    }

}
