//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ShareManV3.databaseSelfMade
{

    public partial class Share : PersistentBase
    {
        int fID;
        [Key(true)]
        public int ID
        {
            get { return fID; }
            set { SetPropertyValue<int>(nameof(ID), ref fID, value); }
        }
        string fISIN;
        [Indexed(Name = @"UniqueISIN", Unique = true)]
        public string ISIN
        {
            get { return fISIN; }
            set { SetPropertyValue<string>(nameof(ISIN), ref fISIN, value); }
        }
        string fName;
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        bool fAusThe;
        public bool AusThe
        {
            get { return fAusThe; }
            set { SetPropertyValue<bool>(nameof(AusThe), ref fAusThe, value); }
        }
        DateTime fLetzteHauptversammlung;
        public DateTime LetzteHauptversammlung
        {
            get { return fLetzteHauptversammlung; }
            set { SetPropertyValue<DateTime>(nameof(LetzteHauptversammlung), ref fLetzteHauptversammlung, value); }
        }
        DateTime fLetzteDividendeDate;
        public DateTime LetzteDividendeDate
        {
            get { return fLetzteDividendeDate; }
            set { SetPropertyValue<DateTime>(nameof(LetzteDividendeDate), ref fLetzteDividendeDate, value); }
        }
        double fLetzteDividendeValue;
        public double LetzteDividendeValue
        {
            get { return fLetzteDividendeValue; }
            set { SetPropertyValue<double>(nameof(LetzteDividendeValue), ref fLetzteDividendeValue, value); }
        }
        string fNotes;
        public string Notes
        {
            get { return fNotes; }
            set { SetPropertyValue<string>(nameof(Notes), ref fNotes, value); }
        }
        Div_Intervall fDiv_Intervall;
        [Association(@"ShareReferencesDiv_Intervall")]
        public Div_Intervall Div_Intervall
        {
            get { return fDiv_Intervall; }
            set { SetPropertyValue<Div_Intervall>(nameof(Div_Intervall), ref fDiv_Intervall, value); }
        }
        StockExchange fBörse;
        [Association(@"ShareReferencesStockExchange")]
        public StockExchange Börse
        {
            get { return fBörse; }
            set { SetPropertyValue<StockExchange>(nameof(Börse), ref fBörse, value); }
        }
        MyCurrency fCurrency;
        [Association(@"ShareReferencesMyCurrency")]
        public MyCurrency Currency
        {
            get { return fCurrency; }
            set { SetPropertyValue<MyCurrency>(nameof(Currency), ref fCurrency, value); }
        }
        Stock_type fStockType;
        [Association(@"ShareReferencesStock_type")]
        public Stock_type StockType
        {
            get { return fStockType; }
            set { SetPropertyValue<Stock_type>(nameof(StockType), ref fStockType, value); }
        }
        string fTeleTextName;
        public string TeleTextName
        {
            get { return fTeleTextName; }
            set { SetPropertyValue<string>(nameof(TeleTextName), ref fTeleTextName, value); }
        }
        [Association(@"Stock_Proce_HistoryReferencesShare")]
        public IList<Stock_Price_History> Stock_Proce_Historys { get { return GetList<Stock_Price_History>(nameof(Stock_Proce_Historys)); } }
    }

}
