//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ShareManV3.databaseSelfMade
{

    public partial class StockExchange : PersistentBase
    {
        int fSEID;
        [Key(true)]
        public int SEID
        {
            get { return fSEID; }
            set { SetPropertyValue<int>(nameof(SEID), ref fSEID, value); }
        }
        string fTradename;
        [Indexed(Name = @"UniqueTradeName", Unique = true)]
        public string Tradename
        {
            get { return fTradename; }
            set { SetPropertyValue<string>(nameof(Tradename), ref fTradename, value); }
        }
        string fOrt;
        public string Ort
        {
            get { return fOrt; }
            set { SetPropertyValue<string>(nameof(Ort), ref fOrt, value); }
        }
        [Association(@"ShareReferencesStockExchange")]
        public IList<Share> Shares { get { return GetList<Share>(nameof(Shares)); } }
    }

}
