//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ShareManV3.databaseSelfMade
{

    public partial class Stock_Price_History : PersistentBase
    {
        int fSPHID;
        [Key(true)]
        public int SPHID
        {
            get { return fSPHID; }
            set { SetPropertyValue<int>(nameof(SPHID), ref fSPHID, value); }
        }
        Share fshare;
        [Indexed(@"Date", Name = @"UniqueCombo", Unique = true)]
        [Association(@"Stock_Proce_HistoryReferencesShare")]
        public Share share
        {
            get { return fshare; }
            set { SetPropertyValue<Share>(nameof(share), ref fshare, value); }
        }
        DateTime fDate;
        public DateTime Date
        {
            get { return fDate; }
            set { SetPropertyValue<DateTime>(nameof(Date), ref fDate, value); }
        }
        double fPrice;
        public double Price
        {
            get { return fPrice; }
            set { SetPropertyValue<double>(nameof(Price), ref fPrice, value); }
        }
        string fNotes;
        public string Notes
        {
            get { return fNotes; }
            set { SetPropertyValue<string>(nameof(Notes), ref fNotes, value); }
        }
    }

}
