//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ShareManV3.databaseSelfMade
{

    public partial class Stock_type : PersistentBase
    {
        int fSTID;
        [Key(true)]
        public int STID
        {
            get { return fSTID; }
            set { SetPropertyValue<int>(nameof(STID), ref fSTID, value); }
        }
        string fShareType;
        [Indexed(Name = @"UniqueShareType", Unique = true)]
        public string ShareType
        {
            get { return fShareType; }
            set { SetPropertyValue<string>(nameof(ShareType), ref fShareType, value); }
        }
        [Association(@"ShareReferencesStock_type")]
        public IList<Share> Shares { get { return GetList<Share>(nameof(Shares)); } }
    }

}
